import { useState, useCallback, useMemo } from 'react';

// ADF4350 Register Calculator & ESP32-C3 Code Generator

interface PinConfig {
  mosi: number;
  sclk: number;
  le: number;
  ce: number;
  muxout: number;
}

interface SynthParams {
  refFreq: number;       // Reference frequency in MHz
  outputFreq: number;    // Desired output frequency in MHz
  refDoubler: boolean;
  refDiv2: boolean;
  rCounter: number;
  channelSpacing: number; // Channel spacing in kHz
}

interface RegisterValues {
  reg0: number;
  reg1: number;
  reg2: number;
  reg3: number;
  reg4: number;
  reg5: number;
  intVal: number;
  fracVal: number;
  modVal: number;
  pfdFreq: number;
  actualFreq: number;
}

function calculateRegisters(params: SynthParams): RegisterValues {
  const { refFreq, outputFreq, refDoubler, refDiv2, rCounter, channelSpacing } = params;

  // Calculate PFD frequency
  let fRef = refFreq;
  if (refDoubler) fRef *= 2;
  if (refDiv2) fRef /= 2;
  const pfdFreq = fRef / rCounter;

  // MOD = channel spacing / PFD * 4096 (or use 4096 as default)
  let modVal = Math.round(channelSpacing * 1000 / pfdFreq);
  if (modVal < 2) modVal = 4096;
  if (modVal > 4095) modVal = 4095;

  // Calculate N divider
  const nTotal = outputFreq / pfdFreq;
  const intVal = Math.floor(nTotal);
  const fracVal = Math.round((nTotal - intVal) * modVal);

  // Actual output frequency
  const actualFreq = ((intVal * modVal + fracVal) / modVal) * pfdFreq;

  // Register 0: [FRAC(12), INT(16), 00]
  const reg0 = ((fracVal & 0xFFF) << 3) | (intVal << 15) | 0;

  // Register 1: [1, Phase(12), Prescaler(1), 0, MOD(12)]
  const phase = 1;
  const prescaler = 1; // 8/9
  const reg1 = (1 << 31) | (phase << 15) | (prescaler << 27) | (modVal << 3) | 1;

  // Register 2: [2, LDF=1, LDP=0, PDN=0, CP=0, MLD=0, R(10), 0, 0, 0]
  const cpGain = 0; // 2.5mA
  const reg2 = (2 << 29) | (1 << 8) | (cpGain << 9) | (rCounter << 14) | 2;

  // Register 3: [3, CSR=1, 0, 0, 0, 0, 0, Phase12bit(12)]
  const reg3 = (3 << 29) | (1 << 18) | 3;

  // Register 4: [4, FB=1, DIVSEL=0, DIV2=0, 0, 0, 0, VCO=0, MTLD=0, AUX=0, AuxPwr=0, RFEn=1, RFPwr=3]
  const feedbackSelect = 1; // Fundamentals
  const vcoPowerDown = 0;
  const mtld = 1;
  const auxOutputEnable = 0;
  const rfOutputEnable = 1;
  const rfOutputPower = 3; // +5dBm
  const reg4 = (4 << 29) | (feedbackSelect << 23) | (vcoPowerDown << 11) |
    (mtld << 10) | (auxOutputEnable << 8) | (rfOutputEnable << 5) | (rfOutputPower << 3) | 4;

  // Register 5: [5, LD=1, 0, 0, Muxout(3)]
  const ldPinMode = 1; // Digital lock detect
  const muxout = 1; // Digital lock detect
  const reg5 = (5 << 29) | (ldPinMode << 22) | (muxout << 19) | 5;

  return {
    reg0, reg1, reg2, reg3, reg4, reg5,
    intVal, fracVal, modVal, pfdFreq, actualFreq
  };
}

function generateCode(pins: PinConfig, regs: RegisterValues, params: SynthParams): string {
  return `/*
 * ADF4350 Synthesizer Control - ESP32-C3
 * Generated by ADF4350 Controller Tool
 * 
 * Target Frequency: ${params.outputFreq.toFixed(3)} MHz
 * Reference: ${params.refFreq} MHz
 * PFD: ${regs.pfdFreq.toFixed(3)} MHz
 * Actual Output: ${regs.actualFreq.toFixed(3)} MHz
 * INT: ${regs.intVal}, FRAC: ${regs.fracVal}, MOD: ${regs.modVal}
 */

#include <Arduino.h>
#include <SPI.h>

// Pin Configuration
#define ADF4350_MOSI    ${pins.mosi}   // SPI MOSI (SDATA)
#define ADF4350_SCLK    ${pins.sclk}   // SPI Clock (SCLK)
#define ADF4350_LE      ${pins.le}     // Load Enable (LE)
#define ADF4350_CE      ${pins.ce}     // Chip Enable (CE) - active HIGH
#define ADF4350_MUXOUT  ${pins.muxout} // MUXOUT - Lock Detect

// ADF4350 Register Values
// Register 0: INT=${regs.intVal}, FRAC=${regs.fracVal}
uint32_t adf4350_regs[6] = {
  0x${regs.reg0.toString(16).toUpperCase().padStart(8, '0')},  // Reg 0
  0x${regs.reg1.toString(16).toUpperCase().padStart(8, '0')},  // Reg 1
  0x${regs.reg2.toString(16).toUpperCase().padStart(8, '0')},  // Reg 2
  0x${regs.reg3.toString(16).toUpperCase().padStart(8, '0')},  // Reg 3
  0x${regs.reg4.toString(16).toUpperCase().padStart(8, '0')},  // Reg 4
  0x${regs.reg5.toString(16).toUpperCase().padStart(8, '0')}   // Reg 5
};

void adf4350_init() {
  // Configure pins
  pinMode(ADF4350_LE, OUTPUT);
  pinMode(ADF4350_CE, OUTPUT);
  pinMode(ADF4350_MUXOUT, INPUT);
  
  digitalWrite(ADF4350_LE, HIGH);  // LE inactive
  digitalWrite(ADF4350_CE, HIGH);  // CE active (chip enabled)
  
  // Initialize SPI
  // ADF4350: CPOL=0, CPHA=0, MSB first, max 20MHz
  SPI.begin(ADF4350_SCLK, -1, ADF4350_MOSI, ADF4350_LE);
  SPI.setFrequency(10000000);  // 10 MHz SPI clock
  SPI.setBitOrder(MSBFIRST);
  SPI.setDataMode(SPI_MODE0);
  
  delay(100);
  
  // Initialize ADF4350 - write all registers in order
  // Must write Reg5, then Reg4, Reg3, Reg2, Reg1, Reg0
  adf4350_write_all();
}

void adf4350_write_reg(uint32_t data) {
  digitalWrite(ADF4350_LE, LOW);
  
  // Send 32 bits, MSB first
  SPI.transfer((data >> 24) & 0xFF);
  SPI.transfer((data >> 16) & 0xFF);
  SPI.transfer((data >> 8) & 0xFF);
  SPI.transfer(data & 0xFF);
  
  digitalWrite(ADF4350_LE, HIGH);
  delayMicroseconds(1);  // LE pulse width minimum
}

void adf4350_write_all() {
  // Write registers in recommended order: 5, 4, 3, 2, 1, 0
  for (int i = 5; i >= 0; i--) {
    adf4350_write_reg(adf4350_regs[i]);
    delayMicroseconds(100);
  }
}

void adf4350_update_frequency(uint32_t newReg0) {
  // To change frequency, only need to update Reg0 and Reg1
  adf4350_regs[0] = newReg0;
  adf4350_write_reg(adf4350_regs[1]);  // Reg1 first
  delayMicroseconds(100);
  adf4350_write_reg(adf4350_regs[0]);  // Then Reg0
}

bool adf4350_is_locked() {
  return digitalRead(ADF4350_MUXOUT) == HIGH;
}

void adf4350_power_down() {
  // Set PDN bit in Register 2
  adf4350_regs[2] |= (1 << 27);  // Power-down bit
  adf4350_write_reg(adf4350_regs[2]);
}

void adf4350_power_up() {
  // Clear PDN bit in Register 2
  adf4350_regs[2] &= ~(1 << 27);
  adf4350_write_reg(adf4350_regs[2]);
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  
  Serial.println("ADF4350 Synthesizer Controller");
  Serial.println("ESP32-C3 + ADF4350");
  Serial.println("========================");
  Serial.print("Target: ${params.outputFreq.toFixed(3)} MHz");
  Serial.print("  PFD: ${regs.pfdFreq.toFixed(3)} MHz");
  Serial.println();
  Serial.print("INT: ${regs.intVal}  FRAC: ${regs.fracVal}  MOD: ${regs.modVal}");
  Serial.println();
  
  adf4350_init();
  
  Serial.println("ADF4350 initialized. Waiting for lock...");
  
  // Wait for PLL lock
  unsigned long timeout = millis() + 5000;
  while (!adf4350_is_locked() && millis() < timeout) {
    delay(10);
  }
  
  if (adf4350_is_locked()) {
    Serial.println("PLL LOCKED!");
  } else {
    Serial.println("Lock timeout!");
  }
}

void loop() {
  // Example: sweep frequencies
  // Uncomment to enable frequency sweep
  
  /*
  static uint32_t sweepIndex = 0;
  uint32_t sweepFreqs[] = {
    // Add your frequencies here (as Reg0 values)
    0x${regs.reg0.toString(16).toUpperCase().padStart(8, '0')},
  };
  
  adf4350_update_frequency(sweepFreqs[sweepIndex]);
  sweepIndex = (sweepIndex + 1) % (sizeof(sweepFreqs)/sizeof(sweepFreqs[0]));
  
  delay(100);  // Wait for lock
  
  if (!adf4350_is_locked()) {
    Serial.println("WARNING: Not locked!");
  }
  */
  
  delay(1000);
}
`;
}

function App() {
  const [pins, setPins] = useState<PinConfig>({
    mosi: 7,
    sclk: 4,
    le: 5,
    ce: 6,
    muxout: 3
  });

  const [params, setParams] = useState<SynthParams>({
    refFreq: 25,
    outputFreq: 435.0,
    refDoubler: false,
    refDiv2: false,
    rCounter: 1,
    channelSpacing: 25
  });

  const [activeTab, setActiveTab] = useState<'calc' | 'code' | 'pins'>('calc');
  const [copied, setCopied] = useState(false);

  const registers = useMemo(() => calculateRegisters(params), [params]);
  const code = useMemo(() => generateCode(pins, registers, params), [pins, registers, params]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [code]);

  const updatePin = (key: keyof PinConfig, value: number) => {
    setPins(prev => ({ ...prev, [key]: value }));
  };

  const updateParam = (key: keyof SynthParams, value: number | boolean) => {
    setParams(prev => ({ ...prev, [key]: value }));
  };

  return (
    <div className="min-h-screen bg-gray-900 text-gray-100">
      {/* Header */}
      <header className="bg-gradient-to-r from-blue-900 to-indigo-900 border-b border-blue-700">
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex items-center gap-3">
            <div className="text-3xl">📡</div>
            <div>
              <h1 className="text-2xl font-bold text-white">ADF4350 Controller</h1>
              <p className="text-blue-300 text-sm">ESP32-C3 Synthesizer Control Tool</p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-6">
        {/* Tab Navigation */}
        <div className="flex gap-2 mb-6">
          <button
            onClick={() => setActiveTab('calc')}
            className={`px-4 py-2 rounded-lg font-medium transition-all ${
              activeTab === 'calc'
                ? 'bg-blue-600 text-white shadow-lg'
                : 'bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700'
            }`}
          >
            🔢 Калькулятор
          </button>
          <button
            onClick={() => setActiveTab('pins')}
            className={`px-4 py-2 rounded-lg font-medium transition-all ${
              activeTab === 'pins'
                ? 'bg-blue-600 text-white shadow-lg'
                : 'bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700'
            }`}
          >
            🔌 Распиновка
          </button>
          <button
            onClick={() => setActiveTab('code')}
            className={`px-4 py-2 rounded-lg font-medium transition-all ${
              activeTab === 'code'
                ? 'bg-blue-600 text-white shadow-lg'
                : 'bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700'
            }`}
          >
            💻 Код
          </button>
        </div>

        {/* Calculator Tab */}
        {activeTab === 'calc' && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Input Parameters */}
            <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
              <h2 className="text-lg font-semibold text-blue-400 mb-4">⚙️ Параметры синтезатора</h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm text-gray-400 mb-1">
                    Опорная частота (MHz)
                  </label>
                  <input
                    type="number"
                    value={params.refFreq}
                    onChange={e => updateParam('refFreq', parseFloat(e.target.value) || 0)}
                    className="w-full bg-gray-900 border border-gray-600 rounded-lg px-3 py-2 text-white focus:border-blue-500 focus:outline-none"
                    step="0.1"
                  />
                </div>

                <div>
                  <label className="block text-sm text-gray-400 mb-1">
                    Выходная частота (MHz)
                  </label>
                  <input
                    type="number"
                    value={params.outputFreq}
                    onChange={e => updateParam('outputFreq', parseFloat(e.target.value) || 0)}
                    className="w-full bg-gray-900 border border-gray-600 rounded-lg px-3 py-2 text-white focus:border-blue-500 focus:outline-none"
                    step="0.001"
                  />
                </div>

                <div>
                  <label className="block text-sm text-gray-400 mb-1">
                    Счётчик R (делитель опорной)
                  </label>
                  <input
                    type="number"
                    value={params.rCounter}
                    onChange={e => updateParam('rCounter', parseInt(e.target.value) || 1)}
                    className="w-full bg-gray-900 border border-gray-600 rounded-lg px-3 py-2 text-white focus:border-blue-500 focus:outline-none"
                    min="1"
                    max="16383"
                  />
                </div>

                <div>
                  <label className="block text-sm text-gray-400 mb-1">
                    Шаг канала (kHz)
                  </label>
                  <input
                    type="number"
                    value={params.channelSpacing}
                    onChange={e => updateParam('channelSpacing', parseFloat(e.target.value) || 25)}
                    className="w-full bg-gray-900 border border-gray-600 rounded-lg px-3 py-2 text-white focus:border-blue-500 focus:outline-none"
                    step="0.1"
                  />
                </div>

                <div className="flex gap-6">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={params.refDoubler}
                      onChange={e => updateParam('refDoubler', e.target.checked)}
                      className="w-4 h-4 rounded bg-gray-700 border-gray-600 text-blue-600 focus:ring-blue-500"
                    />
                    <span className="text-sm text-gray-300">Удвоитель опорной</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={params.refDiv2}
                      onChange={e => updateParam('refDiv2', e.target.checked)}
                      className="w-4 h-4 rounded bg-gray-700 border-gray-600 text-blue-600 focus:ring-blue-500"
                    />
                    <span className="text-sm text-gray-300">Делитель /2</span>
                  </label>
                </div>
              </div>
            </div>

            {/* Register Values */}
            <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
              <h2 className="text-lg font-semibold text-green-400 mb-4">📋 Регистры ADF4350</h2>
              
              <div className="space-y-3">
                <div className="bg-gray-900 rounded-lg p-3 border border-gray-700">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Register 0 (INT/FRAC)</span>
                    <span className="font-mono text-green-400">0x{registers.reg0.toString(16).toUpperCase().padStart(8, '0')}</span>
                  </div>
                </div>
                <div className="bg-gray-900 rounded-lg p-3 border border-gray-700">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Register 1 (MOD/Phase)</span>
                    <span className="font-mono text-green-400">0x{registers.reg1.toString(16).toUpperCase().padStart(8, '0')}</span>
                  </div>
                </div>
                <div className="bg-gray-900 rounded-lg p-3 border border-gray-700">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Register 2 (Control)</span>
                    <span className="font-mono text-green-400">0x{registers.reg2.toString(16).toUpperCase().padStart(8, '0')}</span>
                  </div>
                </div>
                <div className="bg-gray-900 rounded-lg p-3 border border-gray-700">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Register 3 (CSR/Phase)</span>
                    <span className="font-mono text-green-400">0x{registers.reg3.toString(16).toUpperCase().padStart(8, '0')}</span>
                  </div>
                </div>
                <div className="bg-gray-900 rounded-lg p-3 border border-gray-700">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Register 4 (Output/VCO)</span>
                    <span className="font-mono text-green-400">0x{registers.reg4.toString(16).toUpperCase().padStart(8, '0')}</span>
                  </div>
                </div>
                <div className="bg-gray-900 rounded-lg p-3 border border-gray-700">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Register 5 (LD/Muxout)</span>
                    <span className="font-mono text-green-400">0x{registers.reg5.toString(16).toUpperCase().padStart(8, '0')}</span>
                  </div>
                </div>
              </div>

              {/* Summary */}
              <div className="mt-4 bg-blue-900/30 rounded-lg p-4 border border-blue-700">
                <h3 className="text-sm font-semibold text-blue-300 mb-2">📊 Результат расчёта</h3>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="text-gray-400">PFD частота:</div>
                  <div className="text-white font-mono">{registers.pfdFreq.toFixed(3)} MHz</div>
                  <div className="text-gray-400">INT значение:</div>
                  <div className="text-white font-mono">{registers.intVal}</div>
                  <div className="text-gray-400">FRAC значение:</div>
                  <div className="text-white font-mono">{registers.fracVal}</div>
                  <div className="text-gray-400">MOD значение:</div>
                  <div className="text-white font-mono">{registers.modVal}</div>
                  <div className="text-gray-400">Реальная частота:</div>
                  <div className="text-yellow-400 font-mono font-bold">{registers.actualFreq.toFixed(6)} MHz</div>
                  <div className="text-gray-400">Ошибка:</div>
                  <div className={`font-mono ${Math.abs(registers.actualFreq - params.outputFreq) < 0.001 ? 'text-green-400' : 'text-red-400'}`}>
                    {((registers.actualFreq - params.outputFreq) * 1000).toFixed(3)} kHz
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Pins Tab */}
        {activeTab === 'pins' && (
          <div className="max-w-2xl mx-auto">
            <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
              <h2 className="text-lg font-semibold text-orange-400 mb-4">🔌 Распиновка ESP32-C3 → ADF4350</h2>
              
              <div className="space-y-4">
                <div className="bg-gray-900 rounded-lg p-4 border border-gray-700">
                  <div className="grid grid-cols-3 gap-4 items-center">
                    <div>
                      <label className="text-sm text-gray-400 block mb-1">MOSI (SDATA)</label>
                      <span className="text-xs text-gray-500">Данные → ADF4350</span>
                    </div>
                    <div className="text-center text-gray-500">→</div>
                    <input
                      type="number"
                      value={pins.mosi}
                      onChange={e => updatePin('mosi', parseInt(e.target.value) || 0)}
                      className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-white text-center focus:border-orange-500 focus:outline-none"
                      min="0"
                      max="21"
                    />
                  </div>
                </div>

                <div className="bg-gray-900 rounded-lg p-4 border border-gray-700">
                  <div className="grid grid-cols-3 gap-4 items-center">
                    <div>
                      <label className="text-sm text-gray-400 block mb-1">SCLK (CLK)</label>
                      <span className="text-xs text-gray-500">Тактирование</span>
                    </div>
                    <div className="text-center text-gray-500">→</div>
                    <input
                      type="number"
                      value={pins.sclk}
                      onChange={e => updatePin('sclk', parseInt(e.target.value) || 0)}
                      className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-white text-center focus:border-orange-500 focus:outline-none"
                      min="0"
                      max="21"
                    />
                  </div>
                </div>

                <div className="bg-gray-900 rounded-lg p-4 border border-gray-700">
                  <div className="grid grid-cols-3 gap-4 items-center">
                    <div>
                      <label className="text-sm text-gray-400 block mb-1">LE (Latch Enable)</label>
                      <span className="text-xs text-gray-500">Защёлка регистра</span>
                    </div>
                    <div className="text-center text-gray-500">→</div>
                    <input
                      type="number"
                      value={pins.le}
                      onChange={e => updatePin('le', parseInt(e.target.value) || 0)}
                      className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-white text-center focus:border-orange-500 focus:outline-none"
                      min="0"
                      max="21"
                    />
                  </div>
                </div>

                <div className="bg-gray-900 rounded-lg p-4 border border-gray-700">
                  <div className="grid grid-cols-3 gap-4 items-center">
                    <div>
                      <label className="text-sm text-gray-400 block mb-1">CE (Chip Enable)</label>
                      <span className="text-xs text-gray-500">Включение чипа</span>
                    </div>
                    <div className="text-center text-gray-500">→</div>
                    <input
                      type="number"
                      value={pins.ce}
                      onChange={e => updatePin('ce', parseInt(e.target.value) || 0)}
                      className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-white text-center focus:border-orange-500 focus:outline-none"
                      min="0"
                      max="21"
                    />
                  </div>
                </div>

                <div className="bg-gray-900 rounded-lg p-4 border border-gray-700">
                  <div className="grid grid-cols-3 gap-4 items-center">
                    <div>
                      <label className="text-sm text-gray-400 block mb-1">MUXOUT (Lock Detect)</label>
                      <span className="text-xs text-gray-500">← Статус от ADF4350</span>
                    </div>
                    <div className="text-center text-gray-500">←</div>
                    <input
                      type="number"
                      value={pins.muxout}
                      onChange={e => updatePin('muxout', parseInt(e.target.value) || 0)}
                      className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-white text-center focus:border-orange-500 focus:outline-none"
                      min="0"
                      max="21"
                    />
                  </div>
                </div>
              </div>

              {/* Pin Diagram */}
              <div className="mt-6 bg-gray-900 rounded-lg p-4 border border-gray-700">
                <h3 className="text-sm font-semibold text-gray-300 mb-3">📌 Схема подключения</h3>
                <pre className="text-xs text-gray-400 font-mono leading-relaxed overflow-x-auto">
{`  ESP32-C3          ADF4350
  ────────          ───────
  GPIO${pins.mosi.toString().padStart(2, ' ')} ─────────── SDATA (MOSI)
  GPIO${pins.sclk.toString().padStart(2, ' ')} ─────────── SCLK
  GPIO${pins.le.toString().padStart(2, ' ')} ─────────── LE
  GPIO${pins.ce.toString().padStart(2, ' ')} ─────────── CE
  GPIO${pins.muxout.toString().padStart(2, ' ')} ←────────── MUXOUT
  
  3.3V ────────────── AVDD, DVDD
  GND  ────────────── GND`}
                </pre>
              </div>

              <div className="mt-4 p-4 bg-yellow-900/30 rounded-lg border border-yellow-700">
                <p className="text-sm text-yellow-300">
                  ⚠️ <strong>Внимание:</strong> ADF4350 работает с логикой 3.3V. 
                  Убедитесь, что уровни сигналов ESP32-C3 (3.3V) совместимы.
                  Питание AVDD = 3.0-3.6V, DVDD = 2.7-3.6V.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Code Tab */}
        {activeTab === 'code' && (
          <div className="bg-gray-800 rounded-xl border border-gray-700 overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 bg-gray-900 border-b border-gray-700">
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-400">📄 adf4350_esp32c3.ino</span>
                <span className="text-xs bg-green-800 text-green-300 px-2 py-0.5 rounded">Arduino</span>
              </div>
              <button
                onClick={handleCopy}
                className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-all ${
                  copied
                    ? 'bg-green-600 text-white'
                    : 'bg-blue-600 hover:bg-blue-500 text-white'
                }`}
              >
                {copied ? '✓ Скопировано!' : '📋 Копировать'}
              </button>
            </div>
            <div className="p-4 overflow-x-auto max-h-[70vh] overflow-y-auto">
              <pre className="text-sm font-mono text-gray-300 whitespace-pre">
                {code}
              </pre>
            </div>
          </div>
        )}

        {/* Info Section */}
        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-gray-800 rounded-xl p-4 border border-gray-700">
            <h3 className="text-sm font-semibold text-blue-400 mb-2">📐 Формула</h3>
            <p className="text-xs text-gray-400 font-mono">
              RFout = [(INT × MOD) + FRAC] × fPFD / MOD
            </p>
            <p className="text-xs text-gray-500 mt-1">
              fPFD = fREF × (1+D) / (R × (1+÷2))
            </p>
          </div>
          <div className="bg-gray-800 rounded-xl p-4 border border-gray-700">
            <h3 className="text-sm font-semibold text-green-400 mb-2">📡 Диапазон ADF4350</h3>
            <p className="text-xs text-gray-400">
              Выход: 34.6 – 4400 MHz (с внешним VCO до 6.8 GHz)
            </p>
            <p className="text-xs text-gray-500 mt-1">
              PFD: до 32 MHz (100 MHz с VCO ×2)
            </p>
          </div>
          <div className="bg-gray-800 rounded-xl p-4 border border-gray-700">
            <h3 className="text-sm font-semibold text-orange-400 mb-2">⚡ SPI параметры</h3>
            <p className="text-xs text-gray-400">
              CPOL=0, CPHA=0, MSB first
            </p>
            <p className="text-xs text-gray-500 mt-1">
              Max CLK: 20 MHz | 32-bit регистры
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="mt-12 border-t border-gray-800 py-4">
        <div className="max-w-6xl mx-auto px-4 text-center text-sm text-gray-500">
          ADF4350 Controller Tool • ESP32-C3 Code Generator
        </div>
      </footer>
    </div>
  );
}

export default App;
